import { ensureDir, pathExists, readFile } from 'fs-extra'
import writeFileAtomic from 'write-file-atomic'
import { dirname } from 'node:path'

const MISSION_SCRIPTING_TRIGGER = `dofile(lfs.writedir()..'Scripts/dcs-dropzone/MissionScripting.lua')`

const FILE_HEADER = `\
-- This file is automatically generated by DCS DROPZONE
-- Do not edit this file manually as it will be overwritten
-- This file should be called at the top (before '--Sanitize Mission Scripting environment') of the DCS MissionScripting.lua file:
-- ${MISSION_SCRIPTING_TRIGGER}

function dofileifexist(filePath)
    local file = io.open(filePath, "r")
    if file then
        env.info("[dcs-dropzone] - Running dofile: " .. filePath)
        file:close()
        dofile(filePath)
    else
        env.warning("[dcs-dropzone] - Attempted to dofile but file was not found: " .. filePath)
    end
end
`

const getLineForScript = (id: string, symlinkPath: string) => `\
-- ${id}
dofileifexist([[${symlinkPath}]])
`

export class DropzoneMissionScriptingLua {
  static readonly MISSION_SCRIPTING_TRIGGER = MISSION_SCRIPTING_TRIGGER
  private scripts: { id: string; symlinkPath: string }[] = []

  get content(): string {
    return this.fileContent
  }

  get abspath(): string {
    return this.path
  }

  constructor(
    private path: string,
    private fileContent: string
  ) {}

  addScripts(scripts: { id: string; symlinkPath: string }[]): void {
    this.scripts = [...this.scripts, ...scripts]
    this.build()
  }

  build() {
    const lines = this.scripts.map((it) => getLineForScript(it.id, it.symlinkPath))
    this.fileContent = [FILE_HEADER, ...lines].join('\n')
  }

  async write(): Promise<void> {
    await ensureDir(dirname(this.path))
    await writeFileAtomic(this.path, this.fileContent)
  }

  static async fromFile(abspath: string): Promise<DropzoneMissionScriptingLua> {
    let content = ''
    if (await pathExists(abspath)) {
      content = await readFile(abspath, 'utf-8')
    }

    return new DropzoneMissionScriptingLua(abspath, content)
  }
}
