import { describe, expect, it, vi } from 'vitest'
import { readFile, pathExists } from 'fs-extra'
import writeFileAtomic from 'write-file-atomic'
import { DropzoneMissionScriptingLua } from './dropzone-mission-scripting-lua'

vi.mock('fs-extra', () => ({
  readFile: vi.fn(),
  pathExists: vi.fn()
}))

vi.mock('write-file-atomic', () => ({
  default: vi.fn()
}))

describe('DropzoneMissionScriptingLua', () => {
  it('should build content for scripts correctly', () => {
    const lua = new DropzoneMissionScriptingLua('path', '')
    const assets = [
      { id: '1', symlinkPath: 'path1' },
      { id: '2', symlinkPath: 'path2' }
    ]
    lua.addScripts(assets)
    expect(lua.content).toContain('-- 1\ndofileifexist([[path1]])')
    expect(lua.content).toContain('-- 2\ndofileifexist([[path2]])')
  })

  it('should write content to file', async () => {
    const lua = new DropzoneMissionScriptingLua('path', 'content')
    await lua.write()
    expect(writeFileAtomic).toHaveBeenCalledWith('path', 'content')
  })

  it('should create an instance from file', async () => {
    vi.mocked(pathExists).mockResolvedValue(true as any)
    vi.mocked(readFile).mockResolvedValue('file content' as any)
    const lua = await DropzoneMissionScriptingLua.fromFile('path')
    expect(lua.abspath).toBe('path')
    expect(lua.content).toBe('file content')
  })

  it('should handle empty assets array gracefully', () => {
    const lua = new DropzoneMissionScriptingLua('path', '')
    lua.addScripts([])
    expect(lua.content).toBe(`\
-- This file is automatically generated by DCS DROPZONE
-- Do not edit this file manually as it will be overwritten
-- This file should be called at the top (before '--Sanitize Mission Scripting environment') of the DCS MissionScripting.lua file:
-- dofile(lfs.writedir()..'Scripts/dcs-dropzone/MissionScripting.lua')

function dofileifexist(filePath)
    local file = io.open(filePath, "r")
    if file then
        env.info("[dcs-dropzone] - Running dofile: " .. filePath)
        file:close()
        dofile(filePath)
    else
        env.warning("[dcs-dropzone] - Attempted to dofile but file was not found: " .. filePath)
    end
end
`)
  })

  it('should handle file not existing creating one as necessary', async () => {
    vi.mocked(pathExists).mockResolvedValue(false as any)
    vi.mocked(readFile).mockRejectedValue(new Error('ENOENT'))
    const lua = await DropzoneMissionScriptingLua.fromFile('path')
    expect(lua.content).toBe(``)

    lua.addScripts([
      { id: '1', symlinkPath: 'path1' },
      { id: '2', symlinkPath: 'path2' }
    ])
    lua.addScripts([{ id: '3', symlinkPath: 'path3' }])
    await lua.write()

    expect(writeFileAtomic).toHaveBeenCalledWith(
      'path',
      `\
-- This file is automatically generated by DCS DROPZONE
-- Do not edit this file manually as it will be overwritten
-- This file should be called at the top (before '--Sanitize Mission Scripting environment') of the DCS MissionScripting.lua file:
-- dofile(lfs.writedir()..'Scripts/dcs-dropzone/MissionScripting.lua')

function dofileifexist(filePath)
    local file = io.open(filePath, "r")
    if file then
        env.info("[dcs-dropzone] - Running dofile: " .. filePath)
        file:close()
        dofile(filePath)
    else
        env.warning("[dcs-dropzone] - Attempted to dofile but file was not found: " .. filePath)
    end
end

-- 1
dofileifexist([[path1]])

-- 2
dofileifexist([[path2]])

-- 3
dofileifexist([[path3]])
`
    )
  })
})
