import { dialog, shell } from 'electron'
import { Logger } from '@nestjs/common'

const issueBodyTemplate = (error: Error) => `\

This is an automated error report generated by the application.

- **Error:** ${error.name}
- **Message:** ${error.message}
- **Stack Trace:**
\`\`\`text
${error.stack}
\`\`\`
`

const title = 'Oops! Something Went Wrong'
const message = `\
An unexpected error occurred. Please try the following:

- Restart the application.
- Check your internet connection.
- Raise an issue if the problem persists.

An error report has been prepared for you and opened in the browser to share with the developers, should you choose to do so.
`

export function showError(error: Error) {
  const issueTitle = encodeURIComponent(`Error: ${new Date().toISOString()} Fatal Error Report`)
  const issueBody = encodeURIComponent(issueBodyTemplate(error))

  dialog.showErrorBox(title, message)

  shell.openExternal(
    `https://github.com/flying-dice/dcs-dropzone-mod-manager/issues/new?title=${issueTitle}&body=${issueBody}&labels[]=bug`
  )

  Logger.error(error, 'main')
}
