import { app, dialog, shell } from 'electron'
import { Logger } from '@nestjs/common'
import { config } from '../config'

const issueBodyTemplate = (error: Error, recentLogs: string[]) => `\

This is an automated error report generated by the application.

- **Error:** ${error.name}
- **Message:** ${error.message}
- **Stack Trace:**
\`\`\`text
${error.stack}
\`\`\`
---
[Please describe what you were doing when the error occurred here.]


Please Upload the logs from the following location:
${config.logfile.replace(app.getPath('appData'), '%APPDATA%')}

---
${recentLogs.join('\n')}
---

`

const title = 'Oops! Something Went Wrong'
const message = `\
An unexpected error occurred. Please try the following:

- Restart the application.
- Check your internet connection.
- Raise an issue if the problem persists.

An error report has been prepared for you and opened in the browser to share with the developers, should you choose to do so.
`

export function showError(error: Error, recentLogs: string[]) {
  const issueTitle = encodeURIComponent(`Error: ${new Date().toISOString()} Fatal Error Report`)

  const issueBody = encodeURIComponent(issueBodyTemplate(error, recentLogs))

  dialog.showErrorBox(title, message)

  shell.openExternal(
    `https://github.com/flying-dice/dcs-dropzone-mod-manager/issues/new?labels=bug&title=${issueTitle}&body=${issueBody}`
  )

  Logger.error(error, 'main')
}
