import { describe, expect, it } from 'vitest'
import { generateDropzoneMissionScriptingScript } from './generateDropzoneMissionScriptingScript'
import mockFs from 'mock-fs'

describe('generateDropzoneMissionScriptingScript', () => {
  let result: string
  beforeAll(async () => {
    mockFs({
      'C:/Users/username/Saved Games/DCS/Mods/Scripts/example.lua': '-- A Lua File'
    })

    const paths = [
      {
        id: 'example-mod',
        path: 'C:/Users/username/Saved Games/DCS/Mods/Scripts/example.lua'
      },
      {
        id: 'example-mod-2',
        path: 'C:/Users/username/Saved Games/DCS/Mods/Scripts/example2.lua'
      }
    ]

    result = await generateDropzoneMissionScriptingScript(paths)
  })

  afterAll(() => {
    mockFs.restore()
  })

  it('should generate a valid script', () => {
    expect(result).toMatchInlineSnapshot(`
      "-- This file is automatically generated by DCS DROPZONE
      -- Do not edit this file manually as it will be overwritten
      -- This file should be called at the top (before '--Sanitize Mission Scripting environment') of the DCS MissionScripting.lua file by adding the following line:
      -- dofile(lfs.writedir()..'Scripts/dcs-dropzone_MissionScripting.lua')

      function dofileifexist(filePath)
          local file = io.open(filePath, "r")
          if file then
              env.info("[dcs-dropzone] - Running dofile: " .. filePath)
              file:close()
              dofile(filePath)
          else
              env.warning("[dcs-dropzone] - Attempted to dofile but file was not found: " .. filePath)
          end
      end

      -- ## Start of Scripts ##
      -- example-mod
      dofileifexist([[C:/Users/username/Saved Games/DCS/Mods/Scripts/example.lua]])
      "
    `)
  })

  it('should include valid path', async () => {
    expect(result).toContain('C:/Users/username/Saved Games/DCS/Mods/Scripts/example.lua')
  })

  it('should exclude invalid path', () => {
    expect(result).not.toContain('C:/Users/username/Saved Games/DCS/Mods/Scripts/example2.lua')
  })
})
