name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MAIN_VITE_APTABASE_APP_KEY: ${{ secrets.MAIN_VITE_APTABASE_APP_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: 'Report Coverage'
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
