name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install LUA
        uses: xpol/setup-lua@v0.3
        with:
          lua-version: 5.1
      - name: Install
        run: npm install
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
